language: php

php:
    - 5.6
    - 7.0
    - 7.1

matrix:
  include:
    -
        php: 7
        env: dependencies=lowest
    -
        php: 7
        env: dependencies=highest

cache:
  directories:
    - $HOME/.composer/cache

before_script:
    - travis_retry composer self-update -q
    - if [ -z "$dependencies" ]; then travis_retry composer install; fi;
    - if [ "$dependencies" = "lowest" ]; then travis_retry composer update --prefer-lowest --prefer-stable -n; fi;
    - if [ "$dependencies" = "highest" ]; then travis_retry composer update -n; fi;

script:
    - bin/phpspec run --format=pretty
